### ISSUE TITLE
alcuni spunti

### ISSUE THREAD

**Issue by solyarisoftware** [alterani/appunti#2]
Ciao!
grazie per aver inserito www.convcomp2016.it che è ovviamente la risorsa Italiana più importante 
( ah ah la mia è una visone un pò di parte avendo creato #convcomp2016 :-) )
SCHERZO!

Sì la lista è parziale e va a mio modesto avviso fatta crescere e fatta una piccola tassonomia. 
Se hai voglia potresti portare avanti il repo e fare articolo su convcomp2016!

Alcuni modesti suggerimenti su cose da aggiungere:

1- gli strumenti più diffusi di programmazione "hard-coding"

golang: 
abot https://github.com/itsabot/abot
riprende l'idea delle macchine a stati

BTW,

Ruby
sto sviluppando un microframework che si chiamerà naif. Rilascerò opensource e forse vengo da Paolo a Milano a presentare a Dicembre.

NodeJs
a parte botkit che hai giustamente segnato, ci sono altre cose, impossibile no menzionare i repo di Rob Ellis tra cui superscriptjs (vedi dopo su linguaggi di scripting) 

Io, tra le altre cose... aiuto a tenere aggiornato questo repo/directory di strumenti NLP per linguaggio Ruby:

https://github.com/diasks2/ruby-nlp

dacci un occhio e trovi spunti, a prescindere da linguaggio Ruby.

2- strumenti di scripting, non è possibile menzionare ChatsSript 
(su cui ho scritto articolo: https://medium.freecodecamp.com/chatscript-for-beginners-chatbots-developers-c58bb591da8#.qshjftyol), 

ma ce ne sono altri... superscriptjs, rivescript, AIML/pandorabots :( ... 
prossimamente scriverò articolo comparativo tra varie tecnologie.

3- "AI" asa a Service ... hai citato API.ai ma allora andrebbero citate WIT.ai, Recast.ai, PullString, etc. etc. chi più ne ha pià ne metta. Alessandro Vitale ha scritto mesi fa un bell'articolo comparativo https://medium.com/@Conversate/natural-language-apis-for-bots-e791f090e32f#.5yw3wlfhr

Al momento no mi viene in mente altro, segui www.convcomp2016.it e www.twitter.com/solyarisoftware! Scrivo solo di queste robe ... :)
I hope this help 
giorgio

**Comment by alterani** [comment]
Ciao Giorgio,
non era mia intenzione creare una directory ufficiale o qualcosa di simile. Si trattava di miei appunti personali che ho pensato di condividere con la community. Grazie al tuo contributo rischia di diventare una fonte autorevole 👍 . Ho inserito tutte le segnalazioni suggerite ed ho riclassificato il contenuto.
Sarebbe carino farla diventare una pagina wiki così chiunque potrà aggiungere contenuti. Purtroppo ho mille impegni quindi non so se riesco.
Grazie ancora per la segnalazione ed in bocca al lupo per il tuo framework naif.

**Comment by solyarisoftware** [comment]
Ciao Enrico, 

grazie del lavoro, comunque 👍 

Fare e sopratutto manutenere/aggiornare una directory, per quanto sembri solo un elenco, richiede un lavoro, me ne rendo conto anche solo per il modesto contributo al repo di Kevin Dias: https://github.com/diasks2/ruby-nlp
Sì, è un impegno, anche solo fare una tassonomia ed aggiornarla!

Naif lo presenterò forse a Dicembre (al meetup di Paolo a Milano) ma è cosa da poco, invece ci tengo al blog che abbiamo creato post #convcomp2016, proprio per fare networking tra tutti gli attori: sviluppatrici, sviluppatori, università, enti di ricerca, aziende, tutti 😄 

```
╔══╗
╚╗╔╝
╔╝(¯`v´¯)
╚══`.¸.www.convcomp2016.it - Italian chatbots-community blog.
```

take care
giorgio
